// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_chat from "./routes/api/chat.ts";
import * as $api_code_assist from "./routes/api/code-assist.ts";
import * as $api_email from "./routes/api/email.ts";
import * as $api_generate_title from "./routes/api/generate-title.ts";
import * as $api_translate from "./routes/api/translate.ts";
import * as $index from "./routes/index.tsx";
import * as $ChatInterface from "./islands/ChatInterface.tsx";
import * as $CodeAssistant from "./islands/CodeAssistant.tsx";
import * as $EmailGenerator from "./islands/EmailGenerator.tsx";
import * as $TaskManager from "./islands/TaskManager.tsx";
import * as $TranslateForm from "./islands/TranslateForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/code-assist.ts": $api_code_assist,
    "./routes/api/email.ts": $api_email,
    "./routes/api/generate-title.ts": $api_generate_title,
    "./routes/api/translate.ts": $api_translate,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatInterface.tsx": $ChatInterface,
    "./islands/CodeAssistant.tsx": $CodeAssistant,
    "./islands/EmailGenerator.tsx": $EmailGenerator,
    "./islands/TaskManager.tsx": $TaskManager,
    "./islands/TranslateForm.tsx": $TranslateForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
